project:
  type: book
  output-dir: docs

book:
  title: "R Training 2025"
  author: "Matt Green"
  date: now
  date-format: "dddd D MMM YYYY [at] HH[:]mm[:]ss"
  chapters:
    - todo.qmd
    - index.qmd
    - file_handling.qmd
    - analysis.qmd
    - plots.qmd
    - markdown.qmd
    - natalie.qmd
    - natasha.qmd

format:
  html:
    theme: cosmo
